### ISSUE TITLE
Learn about deploying and editing JupyterBook and Myst sites from within a hub instance

### ISSUE THREAD

**Issue by jmunroe** [2i2c-org/community-showcase#17]
This is initially request for a conversation on how to support and maintain community facing documentation (as currently hosted on https://docs.2i2c.org through RTD) and how that compares/contrasts with a JupyterBook (hosted on GitHub pages).  

This task supports this goal by clarifying the `where` and `how` of community-facing documentation.  We believe that in addition to docs.2i2c.org, community partners have need to host their own documentation sites that are bespoke for their communities.  Do these have to be two separate and independent sites? Is there way to sustainably have the content of docs.2i2c.org be an upstream generic dependency for hub specific documentation?  

Pending the outcome of this discussion, choose a path forward so that this goal can improve our community facing documentation to assist our community champions.

**Comment by jmunroe** [comment]
There is choice to be made here about what exactly we mean when recommending to community who wants a 'JupyterBook' adjacent to their hub. 

1. [JupyterBook](https://jupyterbook.org/en/stable/intro.html) as a opinionated Sphinx distribution. Being Sphinx based, excels at reference software documentation.
2. [Myst Markdown](https://mystmd.org/) as a successor project that has a lot of overlap and compatibility but is future focused. For tutorials, educational textbooks (including with Jupyter Notebooks), a presentation, or scientific paper `mystmd` may be a better fit.

See https://mystmd.org/guide/background for some historical context.

Since part of this goal is skill-building for both @colliand and @jmunroe , we should go with direction of where we think the technology is currently at and where it is mostly likely to grow in to the future: [MyST Markdown](https://mystmd.org/guide)

(As understood by @jmunroe based on a chat with @choldgraf)

**Comment by jmunroe** [comment]
I am going to try following https://mystmd.org/guide/quickstart-jupyter-lab-myst to confirm that round trip editing using JupyterLab is sufficient to edit/update a 'JupyterBook' using a git push/pull workflow.  I'll assume that some minimal GitHub actions may need to be set up to things working as expected.

Once I've got an initial attempt worked out, I am going to ask @colliand to attempt to replicate for the Eddy Symposium.  Based on these experience we we be able to determine if "MystMD" is sufficient to use for this goal or if additional development is still required before the tooling is ready.

**Comment by colliand** [comment]
I attempted to follow the MyST quickstart. My target was to use the Jack Eddy or research-delight (eventually renamed to showcase) hubs to create a skeleton site that is hosted via GitHub pages. I discovered that I don't have access to `node` on either of these machines. As a result, I am not able to install the `myst` CLI.

**Comment by colliand** [comment]
My site is rendering by GitHub pages as a Jekyll site. I found that the `deploy.yml` file generated when I ran `myst init` is located under `.github/workflows`. The workflow for deploying was therefore unknown to GitHub Actions so I suspect there was a default to use Jekyll. 

I added `.github/` to version control and tried to push. I get an error: 

```
! [remote rejected] main -> main (refusing to allow a GitHub App to create or update workflow `.github/workflows/deploy.yml` without `workflows` permission)
error: failed to push some refs to 'https://github.com/colliand/myst-site-deploy'
```

Hmm? I suspect now that I conservatively set the permissions I granted to the `gh_scoped_creds` GitHub app and may need to allow for token-based auth to make changes to workflows.

**Comment by colliand** [comment]
I created the `deploy.yml` directly using GitHub instead of by pushing from the site into the repo. 

I updated the `base_URL` environment variable. I am doing something wrong as the GitHub pages action enters startup failure whenever it tries to run the deploy.yml workflow. This is the error report I'm getting:

```
 Error: .github#L1
actions/checkout@v3, actions/configure-pages@v3, actions/setup-node@v3, actions/upload-pages-artifact@v1, and actions/deploy-pages@v2 are not allowed to be used in colliand/myst-site-deploy. Actions in this workflow must be: within a repository owned by colliand.
```

**Comment by jmunroe** [comment]
My goal here was to explore methods for how to edit JupyterBook like content completely within a JuptyerLab environment.

Lessons based on my explorations:
1. Use JupyterLab's git extensions works as a way to make it easier to push/pull changes. But the git extension does not yet work with JupyterLab 4. **Recommendation: continue with JupyterLab 3 for now.**
2. The JupyterLab myst extension for editing and rendering Myst markdown directly with in a JupyterLab environment works wonderfully: **Recommendation: use the JupyterLab myst markdown extension to allow in-situ editing of myst enable notebooks and markdown files.**
3. The myst cli did not to appear to work out-of-the-box (especially `myst serve`) when running in a JupyterLab environment. However JupyterBook (`jupyter-book`, `jb` cli) has an established history of working completely with in a JupyterLab environment. **Recommendation: Continue to use JupyterBook cli to build the website and revisit the `myst` cli again once additional expertise from the Executable Books project is available.**

This recommendations will guide a task in Sprint 3.
