### ISSUE TITLE
Brainstorm tutorials/demos/documentation that would help communities be successful

### ISSUE THREAD

**Issue by jmunroe** [2i2c-org/community-showcase#19]

**Comment by jmunroe** [comment]
See https://github.com/2i2c-org/meta/issues/718 for context and possible lesson topics.

Actions
- [ ] Schedule a working session between @colliand and @jmunroe to iterate and make the plan more explicit

**Comment by colliand** [comment]
Some resources for general Jupyter/Pangeo usage was assembled for the Jack Eddy Symposium. See https://github.com/jack-eddy-symposium/open-science-methods

**Comment by jmunroe** [comment]
Great list here @colliand.  Now that I see it written out, I start thinking of various ways we could help communities:

- Synchronous demo led by a 2i2c team member
- Synchronous demo led by a 2i2c community partner
- Howto and/or Explainer documentation in our service docs
- Blog post
- Short form video demonstrating the task
- Long form video (async demo) explaining the task in detail
- Section in workshop lesson

**Comment by jmunroe** [comment]
An "introduction to 2i2c hub management" curriculum will be the focus of a Carpentries Lesson Content Development workshop to be help in January. Both @jmunroe and @jnywong will attend that workshop to create content that will be initially targeted at Catalyst Project communities but will be applicable to all 2i2c community partners.

The goal of this issue was to come of with possible topics. I think we should take this list:

+ How to manage access to a 2i2c hub?
+ How to onboard a new user of a 2i2c hub?
+ How to use gh_scoped_creds to enable easy and secure push access to GitHub repos?
+ How to use nbgitpuller?
+ How to customize landing pages?
+ How to use Jupyter's internal messaging system? (Pop ups in Lab after logging in.)
+ How to measure resource usage versus time? Prometheus, Grafana, notebooks that ingest billing and usage data? 
+ How to manage software image(s) for a 2i2c hub?
+ How to get involved and contribute to open source? Upstream Doula.
+ How to use and customize the Linux desktop offering on a 2i2c hub?
+ How and why to use a "database sidecar"?
+ How to use Dask Gateway?
+ How to use GPU for ML?
+ What's the hybrid (HPC + Cloud + Local) future look like?

and add it as a page in the Community Showcase Handbook to document the kinds of these we want to showcase.

For Sprint 3, I will assign to @colliand the task adding a new page (markdown document) to the Community Showcase Handbook with this list of topics.
