### ISSUE TITLE
How does jupyter-desktop-server work?

### ISSUE THREAD

**Issue by jmunroe** [2i2c-org/community-showcase#2]
What's going on under the hood with jupyter-desktop-server ?

Currently, I am getting a 500 : Internal Server Error 

I'd like to understand more about what is going on when a user clicks 'Desktop' from within Jupyter Lab.

Is it possible for the user to see output, error logs, or other tracing information?

Can we deploy a Desktop-Server that does not require JupyterLab at all?

**Comment by yuvipanda** [comment]
You're most likely getting the 500 because there's no 'websockify' in the environment.yml file here. See all updates to https://github.com/CryoInTheCloud/hub-image to get that to work.

Good q on what's going on under the hood :) Perhaps we can talk about that tomorrow.

And yes, you can send the user to *any* UI without requiring them to go via JupyterLab, using the magic of '/hub/user-redirect'.

So if you use <hub-url>/hub/user-redirect/desktop, it'll get you directly to the desktop. Same is true for RStudio, etc.

**Comment by damianavila** [comment]
@jmunroe, was @yuvipanda's feedback enough to answer your questions? Can we close this one?

**Comment by consideRatio** [comment]
Great question! I think this is an answer worth putting in [the projects README.md](https://github.com/yuvipanda/jupyter-desktop-server#readme) if you have time Yuvi!

For reference, we've done [a "How it works" topic in jupyterhub-idle-culler as well](https://github.com/jupyterhub/jupyterhub-idle-culler#how-it-works).

**Comment by colliand** [comment]
This question may hijack the thread and merit a separate issue but... how should we decide where to put docs content (like the answer being developed in this thread)? Putting it upstream is good for the upstream project. That said, champions of communities served by 2i2c likely want curated docs that help them understand _their_ hub instead. What are the boundaries and best practices to follow here? We want to build docs, tutorials, events and comms channels to create and nurture a _community of 2i2c hub champions_.  These docs for 2i2c communities should distill upstream docs to enable communities to do open science. I imagine 2i2c's docs to mostly focus on an audience of scientists, users of open source software accessed using platforms operated by 2i2c. In contrast, I imagine upstream docs sites to mostly focus on an audience of software developers or infrastructure engineers. This tension -- who does 2i2c serve with this documentation or software? Open science users vs. Open source projects -- overlaps with ongoing discussions on "standardization" and product-market fit.
