### ISSUE TITLE
Document a workflow for editing JupyterBook within JupyterLab

### ISSUE THREAD

**Issue by jmunroe** [2i2c-org/community-showcase#24]
Base on my explorations of #17, I have a the framework for how I think editing a JupyterBook within a JupyterLab environment could work.

To complete this task
- [x] #22 
- [x] Create a repo2docker based image with JupyterBook , git extension, and myst jupyterlab extensions
- [x] Write up new documentation within the Community Showcase Handbook (@jnywong)
- [x] Test this documentation by making an edit to the Community Showcase Handbook (@colliand)

**Comment by colliand** [comment]
I like that #22 is completed and love the loom video! When will the editing workflow be documented and available for testing? I'd like to use it and integrate into various grant-funded projects.

**Comment by jnywong** [comment]
I agree that the loom video was very instructive to familiarise myself with this workflow! I've tested this on the Community Showcase Hub and currently using this workflow to develop the technical content there to onboard Hub Champions (e.g. see GH comment [here](https://github.com/2i2c-org/community-showcase/issues/23#issuecomment-1880655232))

**Comment by jmunroe** [comment]
There are two paths to pursue here when it comes to authoring/editing JupyterBooks.

1. Document the already working JupyterBook tooling available to support in-JupyterLab authoring/editing of JupyterBooks (using sphinx)
2. Resolve https://github.com/executablebooks/mystmd/issues/302 to support in-JupyterLab authoring/editing of JupyterBooks (using `myst start`)

Giving that there is already a established set of JupyterBooks out there, it makes sense to me that we fully document using the existing JupyterBook tooling a processing for editing JupyterBooks with the sphinx tooling.

I will create a new separate issue for a `myst` based workflow.

**Comment by jmunroe** [comment]
@jnywong Would you add a new section to the Community Showcase Handbook something like
  
'Sharing your content with JupyterBook'

and then add a specific page that documents the workflow for editing an existing JupyterBook from a git repo within the Community Showcase JupyterHub.  The content could follow what I demo'd in that loom video or whatever workflow that has evolved from that this that you are using to author/edit JupyterBook content.

Once @jnywong  has this process documented and available on https://2i2c.org/community-showcase , @colliand should test that workflow and provide feedback.

**Comment by jnywong** [comment]
Also related https://github.com/2i2c-org/community-showcase/pull/63

**Comment by jnywong** [comment]
I'm going to consider this work as completed in this sprint, but feel free to re-open if you feel otherwise.
