### ISSUE TITLE
Purchase a license for Loom

### ISSUE THREAD

**Issue by jmunroe** [2i2c-org/community-showcase#64]
Motivated by creating this [JupyterBook video workflow](https://www.loom.com/share/2ce8dd192072477a9cbf61ea5b253998?sid=54e054df-1c22-4d79-916e-020aad131178) and work being done by @jnywong in  [Handbook Authoring docs](https://2i2c.org/community-showcase/community/content/authoring.html#build-and-preview-your-jupyter-book), we have both found utility in Loom as a screen recorder and it worked the best out of all the other screen recorders we tried. The free 14-day trial allowed video downloads but will expire soon – is there potential to pay for a subscription to continue the documentation work?

To make decision on this purchase, we need to answer the following questions:

1. What's the purpose for Loom? Is it creating internal content, external content? What is the value we hope that it will deliver?
2. What alternatives exist and why is Loom the right choice? (e.g. compared with YouTube, Slack videos, Google Drive videos, etc)
3. What are our hypotheses for why Loom will deliver the value we hope it will?
4. How will we test this hypothesis? What measures will we look for in 1/3/6/12 months to decide if this is still the right choice?
5. Are there any risks to using Loom? E.g., what happens if Loom changes its pricing to be unsustainable for us?
6. Does this change any of 2i2c's standard operating procedures? And if so, where will we document them?

**Comment by jmunroe** [comment]
(TO BE FILLED IN BY ANYONE!)

> 1. What's the purpose for Loom? Is it creating internal content, external content? What is the value we hope that it will deliver?

It will be used for creating screen cast video for usage in community facing documentation and tutorials. It also will be used for internal training and documentation purposes.

> 2. What alternatives exist and why is Loom the right choice? (e.g. compared with YouTube, Slack videos, Google Drive videos, etc)

Loom is being recommend primarily as a screen capture tool.  The primary limitation in the 'free version' 

Article on Loom alternatives: https://clickup.com/blog/loom-alternatives/

> 3. What are our hypotheses for why Loom will deliver the value we hope it will?

> 4. How will we test this hypothesis? What measures will we look for in 1/3/6/12 months to decide if this is still the right choice?

> 5. Are there any risks to using Loom? E.g., what happens if Loom changes its pricing to be unsustainable for us?

> 6. Does this change any of 2i2c's standard operating procedures? And if so, where will we document them?

**Comment by jnywong** [comment]
> 1. What's the purpose for Loom? Is it creating internal content, external content? What is the value we hope that it will deliver?

Mainly screen recording for technical content creation to be shared externally to 2i2c end users.

> 2. What alternatives exist and why is Loom the right choice? (e.g. compared with YouTube, Slack videos, Google Drive videos, etc)

The alternatives listed are video sharing platforms, whereas the Loom pro subscription would allow me to record and  download videos to then embed into our external facing documentation. Another tool that I have used in the past is OBS, which is free but overkill and clunky to use. 

> 3. What are our hypotheses for why Loom will deliver the value we hope it will?

My hypothesis is that Loom is a lightweight tool and its ease of use would facilitate content creation at a higher rate.

> 4. How will we test this hypothesis? What measures will we look for in 1/3/6/12 months to decide if this is still the right choice?

Currently I don't have a base case to test this hypothesis against, but I think it's worth reviewing usage in 3 months time.

> 5. Are there any risks to using Loom? E.g., what happens if Loom changes its pricing to be unsustainable for us?

It's true that Loom have increased their pricing in the past. If we use the monthly plan then this allows some flexibility to opt out after initial review.

> 6. Does this change any of 2i2c's standard operating procedures? And if so, where will we document them?

I will primarily use this tool for developing technical content and there are no 2i2c-wide standard operating procedures for this, which I think is reasonable in this regard.

**Comment by colliand** [comment]
I approve. Please proceed.

**Comment by jnywong** [comment]
Loom license purchased and receipt sent to `receipts@ramp.com`. 

I've added this issue to the Partnerships project board with an end date of May 5 for review in 3 months' time.

**Comment by jnywong** [comment]
@choldgraf it looks like you have to add my email address to the Ramp account for the automatic receipting to work. I've sent you a DM on Slack.

**Comment by jnywong** [comment]
Depending on what the outcome of this process is, I will make an issue to document the relevant change on the Team Compass!

**Comment by choldgraf** [comment]
I've responded in https://github.com/2i2c-org/team-compass/issues/800 with the process @jnywong can follow - thanks for catching that and sorry about the confusion.

Many thanks to @jmunroe and @jnywong for writing up some quick rationales and context for the decision. I look forward to seeing what we can do with Loom! I'm particularly interested in learning about this because "video recording for async communication" is a pain point I often feel.

**Comment by jmunroe** [comment]
This task is completed. There is subsequent task
- [ ]  @jnywong report on experience in 3 months

that needs to be created and scheduled.
