### ISSUE TITLE
Create docs page for gh-scoped-creds

### ISSUE THREAD

**Issue by jmunroe** [2i2c-org/community-showcase#65]
Motivated by the request in https://github.com/leap-stc/leap-stc.github.io/issues/129 , let's create a single markdown which covers the content covered in https://blog.jupyter.org/securely-pushing-to-github-from-a-jupyterhub-3ee42dfdc54f

While documenting `gh-scoped-creds` is generally useful, I think this could be nice specific example of creating a piece of content that could be included in a JupyterBook that 2i2c maintains (community showcase handbook) AND reused downstream by a community partner.

**Comment by jnywong** [comment]
Documentation deployed to https://2i2c.org/community-showcase/user/topics/data/git.html

**Comment by jnywong** [comment]
Currently, the community showcase handbook is a WIP and not publicised. If this piece of documentation is approved for use, then should it be upstreamed to the Service Guide at docs.2i2c.org? Or will this continue to serve as a standalone document for communities to adopt downstream?

**Comment by jnywong** [comment]
A link to the single markdown file as requested in the original comment can be found here: https://github.com/2i2c-org/community-showcase/blob/main/handbook/user/topics/data/git.md

**Comment by jnywong** [comment]
Closing this issue as done and I will turn the question above about how this piece of documentation may be adopted upstream/downstream into a separate issue.
