### ISSUE TITLE
Update documentation and configuration on how to access community-showcase

### ISSUE THREAD

**Issue by jmunroe** [2i2c-org/community-showcase#66]
For team members internal to 2i2c, access to showcase.2i2c.cloud should automatically be granted via  [helm-charts/basehub/values.yaml](https://github.com/2i2c-org/infrastructure/blob/master/helm-charts/basehub/values.yaml)

For people not internal to 2i2c, use the GitHub organization https://github.com/2i2c-community-showcase and set up the appropriate teams

- [ ] Write up this documentation in team-compass
- [x] Remove the old 2i2c-org/Research-Delight-Team team from config file
- [x] Remove the old 2i2c-org/Research-Delight-Team team from 2i2c-org Github org

**Comment by jnywong** [comment]
> Remove the old 2i2c-org/Research-Delight-Team team from config file

https://github.com/2i2c-org/infrastructure/pull/3700
