### ISSUE TITLE
Review Loom subscription after 3 months

### ISSUE THREAD

**Issue by jmunroe** [2i2c-org/community-showcase#69]
- [x] @jnywong to report on usage of Loom and make a recommendation if the service should be continued after the first 3 months

Follows from 
- https://github.com/2i2c-org/community-showcase/issues/64

**Comment by jnywong** [comment]
I've cancelled the Loom subscription (effective from 5 April) early since I have not worked on the community showcase documentation as much as I thought I would compared to 2 months ago.
