### ISSUE TITLE
Add 'Hub Control Panel' in JupyterLab file menu handbook-authoring-image

### ISSUE THREAD

**Issue by jmunroe** [2i2c-org/community-showcase#73]
Ref: https://2i2c.freshdesk.com/a/tickets/1330

I thought @jupyterlab/hub-extension might be needed but it looks like that's no longer required.  So what package or extension does bring in that 'Hub Control Panel' menu item into JupyterLab?

**Comment by jnywong** [comment]
This is not a super urgent request but more of a "nice-to-have" so that users on the Community Showcase have a consistent experience.
